---
- hosts: bit-dev-elk
  become: no
  tasks:
  - name: Clone git repo with ELK coompose
    git:
      repo: 'https://github.com/lukcic-bright/docker-elk'
      dest: /usr/share/elk/docker-elk
      clone: yes
      update: yes
  - name: Create directory for Elastisearch volume
    file:
      path: /usr/share/elk/elasticsearch
      owner: ec2-user
      group: ec2-user
      state: directory  
  - name: Run ELK docker-compose
    shell: docker-compose up -d
    args:
      chdir: /usr/share/elk/docker-elk/