---
- hosts: all
  become: yes
  tasks:
  # Create and mount partition for ELK data
  - name: Install parted
    yum:
      name: parted.x86_64
      state: present 
    
  - name: "Add new partition on /dev/nvme1n1"
    parted: 
      device: /dev/nvme1n1
      number: 1
      part_type: primary
      label: gpt
      name: "ELK_data"
      state: present

  - name: Create filesystem
    filesystem:
      fstype: xfs
      dev: /dev/nvme1n1p1

  - name: Create empty directory
    file:
      path: /usr/share/elk
      state: directory  

  - name: Mount new partition
    mount:
      fstype: xfs
      src: /dev/disk/by-partlabel/ELK_data
      path: /usr/share/elk
      state: mounted  




      